branch-defaults:
  master:
    environment: pneumonia-ppe
    group_suffix: null
environment-defaults:
  pneumonia-ppe:
    branch: null
    repository: null
global:
  application_name: pneumonia-ppe
  branch: null
  default_ec2_keyname: aws-eb-ppe
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
